yatube/about/urls.py
from django.urls import path

from . import views

app_name = "about"

urlpatterns = [
    path("author/", views.AboutAuthor.as_view(), name="author"),
    path("tech/", views.AboutTech.as_view(), name="tech"),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = "posts"

urlpatterns = [
    path("", views.index, name="index"),
    path("group/<slug:slug>/", views.group_posts, name="group_list"),
    path("profile/<str:username>/", views.profile, name="profile"),
    path("posts/<int:post_id>/", views.post_detail, name="post_detail"),
    path("create/", views.post_create, name="post_create"),
    path("posts/<int:post_id>/edit/", views.post_edit, name="post_edit"),
]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeDoneView, PasswordChangeView,
    PasswordResetCompleteView, PasswordResetConfirmView, PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("signup/", views.SignUp.as_view(), name="signup"),
    path(
        "logout/",
        LogoutView.as_view(template_name="users/logged_out.html"),
        name="logout",
    ),
    path(
        "login/",
        LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "password_change/done/",
        PasswordChangeDoneView.as_view(
            template_name="users/password_change_done.html"
        ),
        name="password_change_done",
    ),
    path(
        "password_change/",
        PasswordChangeView.as_view(
            template_name="users/password_change_form.html"
        ),
        name="password_change",
    ),
    path(
        "password_reset/",
        PasswordResetView.as_view(
            template_name="users/password_reset_form.html"
        ),
        name="password_reset_form",
    ),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<auidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("users.urls", namespace="users")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("posts.urls", namespace="posts")),
    path("about/", include("about.urls", namespace="about")),
]
handler404 = "core.views.page_not_found"
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField("Название сообщества", max_length=200)
    slug = models.SlugField("Идентификатор страницы", unique=True)
    description = models.TextField("Описание сообщества")

    class Meta:
        verbose_name = "Группа"
        verbose_name_plural = "Группы"

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name="Текст")
    pub_date = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата публикации",
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name="Группа",
        related_name="posts",
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name="Автор",
        related_name="posts",
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )  

    class Meta:
        ordering = ("-pub_date",)
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def __str__(self):
        return self.text[:15]

yatube/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image")
        labels = {
            "text": "Текст поста",
            "group": "Выберите группу",
        }
        help_texts = {
            "text": "Текст нового поста",
            "group": "Группа, к которой будет относиться пост",
        }

yatube/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("first_name", "last_name", "username", "email")

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthor(TemplateView):
    template_name = "about/author.html"


class AboutTech(TemplateView):
    template_name = "about/tech.html"

yatube/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, "core/404.html", {"path": request.path}, status=404)


def csrf_failure(request, reason=""):
    return render(request, "core/403csrf.html")

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from yatube.settings import POSTS_ON_PAGE

from .forms import PostForm
from .models import Group, Post, User


def paginator_view(request, post_list):
    return Paginator(post_list, POSTS_ON_PAGE).get_page(
        request.GET.get("page"))


def index(request):
    return render(request, "posts/index.html", {
        "page_obj": paginator_view(request, Post.objects.all())
    })


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    return render(request, "posts/group_list.html", {
        "group": group,
        "page_obj": paginator_view(request, group.posts.all())
    })


def profile(request, username):
    user = get_object_or_404(User, username=username)
    return render(request, "posts/profile.html", {
        "author": user,
        "page_obj": paginator_view(request, user.posts.all()),
    })


def post_detail(request, post_id):
    return render(request, "posts/post_detail.html", {
        "post": get_object_or_404(Post, id=post_id)
    })


@login_required
def post_create(request):
    template = "posts/create_post.html"
    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, template, {"form": form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect("posts:profile", username=post.author)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect("posts:post_detail", post_id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post)
    if form.is_valid():
        form.save()
        return redirect("posts:post_detail", post_id=post_id)
    context = {
        "form": form,
        "post_id": post_id,
        "is_edit": True,
    }
    return render(request, "posts/create_post.html", context)

yatube/users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy("posts:index")
    template_name = "users/signup.html"

yatube/templates/about/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
<h1>Привет, я автор</h1>
<p>
  Тут я размещу информацию о себе используя свои умения верстать.
  Картинки, блоки, элементы бустрап. А может быть, просто напишу несколько абзацев текста. 
</p>
{% endblock %} 

yatube/templates/about/tech.html
{% extends "base.html" %}
{% block title %}Технологии{% endblock %}
{% block content %}
{% comment %} Колонки с отступом сверху и снизу {% endcomment %}
<div class="row">
  <h1>Вот что я умею</h1>
  {% comment %}
    Боковой блок со списком технологий 
    Займет всю ширину блока на мобильном
    и 25% при размерах экрана ≥768px
  {% endcomment %}
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        Python
      </li>
      <li class="list-group-item">
        Django
      </li>
    </ul>
  </aside>
  {% comment %}
    Статья  
    Займет всю ширину блока на мобильном
    и 75% при размерах экрана ≥768px
  {% endcomment %}
  <article class="col-12 col-md-9">
    <p>Текст страницы "Технологии"</p>
  </article>
</div>
{% endblock %} 

yatube/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'img/fav/favicon.ico' %}" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/fav/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/fav/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/fav/favicon-16x16.png' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>
      {% block title%}{% endblock %}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container py-5"> 
        {% block content %}{% endblock %}
      </div>
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

yatube/templates/core/403csrf.html
{% extends "base.html" %}
{% block content %}
  <h1>Custom CSRF check error. 403</h1>
{% endblock %}

yatube/templates/includes/footer.html
<p>© {{ year }} Copyright <br> <span style="color:red">Ya</span>tube</p> 

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %} 
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item"> 
          <a class="nav-link 
            {% if view_name == 'about:author' %}
              active
            {% endif %}"
          href="{% url 'about:author' %}"
          >
            Об авторе
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link
            {% if view_name == 'about:tech' %}
              active
            {% endif %}"  
            href="{% url 'about:tech' %}"
          >
          Технологии
        </a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item"> 
            <a class="nav-link
              {% if view_name == 'posts:post_create' %}
                active
              {% endif %}"
              href="{% url 'posts:post_create' %}"
            >
              Новая запись
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light
              {% if view_name == 'users:password_change' %}
                active
              {% endif %}"
              href="{% url 'users:password_change' %}"
            >
              Изменить пароль
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:logout' %}">
              Выйти
            </a>
          </li>
          <li>
            Пользователь:
            <a href="{% url 'posts:profile' user.username %}">
              {{ user.username }}
            </a>
          </li>
        {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light
              {% if view_name == 'users:login' %}
                active
              {% endif %}"
                href="{% url 'users:login' %}"
            >
              Войти
            </a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light
              {% if view_name == 'users:signup' %}
                active
              {% endif %}"
              href="{% url 'users:signup' %}"
            >
              Регистрация
            </a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>      
{% endwith %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% block title %}
  {% if is_edit %} Редактировать пост {% else %} Добавить пост {% endif %} 
{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        {% load user_filters %}
        {% if form.errors %}
          {% for field in form %} 
            {% for error in field.errors %}            
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endfor %}
          {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
              {{ error|escape }}
            </div>
          {% endfor %}
        {% endif %}
        <div class="card-header">
          {% if is_edit %} Редактировать пост {% else %} Добавить пост {% endif %}            
        </div>
        <div class="card-body">      
          <form method="post" enctype="multipart/form-data" action="{% if is_edit %}{% url 'posts:post_edit' post_id %}{% else %}{% url 'posts:post_create' %}{% endif %}" >
            {% csrf_token %}  
            {% for field in form %} 
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                {{ field|addclass:'form-control' }} 
                {% if field.help_text %}
                  <small 
                    id="{{ field.id_for_label }}-help"
                      class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %} Сохранить {% else %} Добавить {% endif %} 
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block content %} 
  <h1>{{ group.title }}</h1>
  <p>{{ group.description | linebreaksbr }}</p>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: 
        <a href="{% url 'posts:profile' post.author.username %}">
          {{ post.author.username }}
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text | linebreaksbr }}</p>   
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
  <h1>Последние обновления на сайте</h1>    
  {% for post in page_obj %}
    <ul>
      <li> Автор: 
        <a href="{% url 'posts:profile' post.author.username %}">
          {% if not post.author.get_full_name %}
            {{ post.author }}
          {% else %}
            {{ post.author.get_full_name }}
          {% endif %}
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text | linebreaks }}</p>   
    {% if post.group %} 
      <a href="{% url 'posts:group_list' post.group.slug %}">#{{ post.group.title }}</a>
    {% endif %}
    <p><a href="{% url 'posts:post_detail' post.id %}">Подробная информация </a></p>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}
{% block content %} 
  <div class="row">
    <aside class="col-12 col-md-3">
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
        {% if post.group %} 
          <li class="list-group-item">
            <a href="{% url 'posts:group_list' post.group.slug %}">#{{ post.group.title }}</a>
          </li>
        {% endif %}
        <li class="list-group-item">
          Автор: 
          <a href="{% url 'posts:profile' post.author.username %}">
            {% if not post.author.get_full_name %}
              {{ post.author }}
            {% else %}
              {{ post.author.get_full_name }}
            {% endif %}
          </a>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Всего постов автора:  <span >{{ post.author.posts.count }}</span>
        </li>
        <li class="list-group-item">
          <a href="{% url 'posts:profile' post.author.username %}">Все посты пользователя</a>
        </li>
      </ul>
    </aside>
    <article class="col-12 col-md-9">
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text | linebreaks }}</p>
      {% if post.author == user %}
        <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
          Редактировать запись
        </a> 
      {% endif %}
    </article>
  </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %}Профайл пользователя {% if not author.get_full_name %}{{ author.username }}{% else %}{{ author.get_full_name }}{% endif %}{% endblock %}
{% block content %}       
  <h1>Все посты пользователя {{ author.get_full_name }}<br>{{ author.username }}</h1>
  <h3>Всего постов: {{author.posts.count}} </h3>  
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: 
          <a href="{% url 'posts:profile' post.author.username %}">
            {% if not post.author.get_full_name %}
              {{ post.author.username }}
            {% else %}
              {{ post.author.get_full_name }}
            {% endif %}
          </a>
        </li>
        <li>
          Дата публикации: {{post.pub_date|date:"d E Y"}} 
        </li>
      </ul>
      <p>
        {{ post.text | linebreaksbr }}
      </p>
      <a href="{% url 'posts:post_detail' post.id %}">Подробная информация </a>
    </article>       
    {% if post.group %} 
      <a href="{% url 'posts:group_list' post.group.slug %}">#{{ post.group.title }}</a>
    {% endif %}        
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %} 
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/users/login.html
{% extends 'base.html' %}
{% block title%}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'users:login' %}">
            {% csrf_token %}         
            <div class="form-group row my-3">
              <label for="id_username">
                Имя пользователя
                <span class="required text-danger">*</span>
              </label>
              <input type="text" name="username" autofocus class="form-control" required id="id_username">
            </div>
            <div class="form-group row my-3">
              <label for="id_password">
                Пароль
                <span class="required text-danger">*</span>
              </label>
              <input type="password" name="password" class="form-control" required id="id_password">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Войти
              </button>
              <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
                Забыли пароль?
              </a>
            </div>
          </form>
        </div> 
      </div> 
    </div>
  </div>
{% endblock %}

yatube/templates/users/password_change_form.html
{% extends 'base.html' %}
{% block title%}Изменение пароля{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Изменить пароль
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'users:password_change' %}">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_old_password">
                Старый пароль
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password1">
                Новый пароль
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_new_password2">
                Подтверждение нового пароля
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Изменить пароль
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}

yatube/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% block title%}Сброс пароля прошёл успешно{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Восстановление пароля завершено
        </div>
        <div class="card-body">
          <p>Ваш пароль был сохранен. Используйте его для входа</p>
          <a href="{% url 'users:login' %}">войти</a>
        </div> 
      </div> 
    </div>
  </div> 
{% endblock %}

yatube/templates/users/password_reset_confirm.html
{% extends 'base.html' %}
{% block title%}Новый пароль{% endblock %}
{% block content %}
  {% load user_filters %}  
  {% if validlink %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Введите новый пароль
          </div>
          <div class="card-body">
            <form method="post" action="{% url 'users:password_reset_confirm' %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_new_password1">
                  Новый пароль        
                  <span class="required text-danger">*</span>        
                </label>    
                <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                <small id="id_new_password1-help" class="form-text text-muted">
                  <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                </small>      
              </div>
              <div class="form-group row my-3 p-3">
                <label for="id_new_password2">
                  Подтверждение нового пароля        
                  <span class="required text-danger">*</span>        
                </label>    
                <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Назначить новый пароль
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
    {% else %}
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Ошибка
          </div>
          <div class="card-body">
            <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
    </div> <!-- row -->
  {% endif %}
{% endblock %}

yatube/templates/users/password_reset_form.html
{% extends 'base.html' %}
{% block title%}Сброс пароля{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
        </div>
        <div class="card-body"> 
          <form method="post" action="{% url 'users:password_reset_form' %}">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_email">
                Адрес электронной почты
                <span class="required text-danger">*</span>
              </label>    
              <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Сбросить пароль
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>  
{% endblock %}

yatube/templates/users/signup.html
{% extends 'base.html' %}
{% block title%}Зарегистрироваться{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            <div class="form-group row my-3 p-3">
              <label for="id_first_name">Имя</label>    
              <input type="text" name="first_name" maxlength="30" class="form-control" id="id_first_name">     
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_last_name">Фамилия</label>    
              <input type="text" name="last_name" maxlength="150" class="form-control" id="id_last_name">
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_username">
                Имя пользователя
                <span class="required text-danger">*</span>
              </label>    
              <input type="text" name="username" maxlength="150" autofocus class="form-control" required id="id_username">
                <small id="id_username-help" class="form-text text-muted">
                  Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.
                </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_email">Адрес электронной почты</label>    
              <input type="email" name="email" maxlength="254" class="form-control" id="id_email">      
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_password1">
                Пароль        
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="password1" class="form-control" required id="id_password1">
              <small id="id_password1-help" class="form-text text-muted">
                <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
              </small>
            </div>
            <div class="form-group row my-3 p-3">
              <label for="id_password2">
                Подтверждение пароля
                <span class="required text-danger">*</span>
              </label>    
              <input type="password" name="password2" class="form-control" required id="id_password2">
              <small id="id_password2-help" class="form-text text-muted">
                Для подтверждения введите, пожалуйста, пароль ещё раз.
              </small>
            </div>
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}